ARG BASE_IMAGE=ghcr.io/lwmacct/250210-cr-docker:v0.10.260731
FROM ${BASE_IMAGE}

COPY smoke.sh /usr/local/bin/nsair-ci-docker-in-docker-smoke
RUN chmod +x /usr/local/bin/nsair-ci-docker-in-docker-smoke
